### PR TITLE
Link to Installing Beta from more pages

### LINKED ISSUE #291: [Docs] Show how to download from GitHub in more places
The first target for anyone with no experience with GitHub, contributing, or browser extensions would probably be the [Installing](https://docs.scratchtools.app/docs/getting-started/installing) page from the docs, which tells you how to install ScratchTools from web stores, but web store installations aren't meant to be for modifying code, in fact, I think the browser might even throw an error if you do. The next obvious place to go to is [Building a Feature](https://docs.scratchtools.app/docs/contributing/building-a-feature), but it says nothing about running ScratchTools or how to test the modified code, and these users will want to test their changes.

**There are a few ways we could solve this:**

- [Installing Beta](https://docs.scratchtools.app/docs/beta) does go through the developer-oriented way to install the extension that you would use to test the changes you made. We could link to it from [Building a Feature](https://docs.scratchtools.app/docs/contributing/building-a-feature) to make sure the user understands how to test their changes.

- We could also add a note to [Installing](https://docs.scratchtools.app/docs/getting-started/installing) that tells you what to do if you plan to make changes or contribute, again, linking to Installing Beta, like the [How do I download ScratchTools? FAQ](https://docs.scratchtools.app/docs/faq#how-do-i-download-scratchtools) sort of does.

- We could also link to those instructions from the [CONTRIBUTING.md](https://github.com/STForScratch/ScratchTools/blob/main/CONTRIBUTING.md) file in this repository.

While we're at it, we should also note that you should be testing your changes before you submit them.

### PR DESCRIPTION
**Pull request by DNin01**
Adds links going to the Installing Beta page to a few other related pages to guide new contributors.

Resolves https://github.com/STForScratch/ScratchTools/issues/291

I also did some bonus grammar fixes.

### CODE REVIEW

**Comment by DNin01** [comment]
@rgantzos Ready to merge?

**Comment by rgantzos** [comment]
> @rgantzos Ready to merge?

There are some unnecessary changes that I need to look over.

**Comment by DNin01** [comment]
@rgantzos Any update? It's been a while since this was opened.

**Comment by DNin01** [comment]
@rgantzos Is this ready to merge?

**Pull request closed without merging**
