### PR TITLE
Fixed link to completely redirect to issues and not repository page

### PR DESCRIPTION
**Pull request by nikeedev**
Fixed wrong link error, found by @stiostudio

### CODE REVIEW

**Review by MaterArc — APPROVED** [review]
Thanks for submitting a pr 😅

**Comment by MaterArc** [comment]
@rgantzos could you merge this? I don't have write access to this repo! Thanks :)

**Comment by nikeedev** [comment]
> Thanks for submitting a pr 😅

No problem! :)

**Comment by nikeedev** [comment]
Why did it get closed @rgantzos…?

**Comment by rgantzos** [comment]
> Why did it get closed @rgantzos…?

I'm pretty sure it's no longer relevant now that the documentation has been rewritten.

**Pull request closed without merging**
